stages:
  - setup
  - test
  - sonarcloud-check

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

# Instala dependências
setup:
  stage: setup
  image: node:18
  cache:
    key: npm-cache
    paths:
      - node_modules/
  script:
    - npm install

# Executa testes
test:
  stage: test
  image: node:18
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends chromium
  script:
    - echo "Executando testes..."
    - npm run test -- --watch=false --browsers=ChromeHeadless
  cache:
    key: npm-cache
    paths:
      - node_modules/
      - .angular/cache/

# Análise do SonarCloud
sonarcloud-check:
  stage: sonarcloud-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: sonar-cache
    paths:
      - .sonar/cache/
  script:
    - echo "Executando análise do SonarCloud..."
    - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN"
  only:
    - merge_requests
    - main
    - develop
