services:
  postgres-db:
    image: postgres:15
    container_name: university-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: university_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: university-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/university_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: default

volumes:
  postgres_data: