stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonarqube
  - deploy

variables:
  SONAR_HOST_URL: "http://192.168.0.10"  # Substitua pelo IP real do servidor SonarQube
  SONAR_LOGIN: "${SONAR_TOKEN}"          # O token de autenticação gerado no SonarQube

build-job:       # Job que roda na fase de build
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:   # Job para rodar testes
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

sonarqube-job:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey="my_project_key" -Dsonar.sources="./src" -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.login="${SONAR_LOGIN}" -Dsonar.language="java"
  only:
    - main


deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
