sonarqube-job:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Running SonarQube analysis..."
    - sonar-scanner -Dsonar.projectKey="my_project_key" -Dsonar.sources="./src" -Dsonar.host.url="http://host.docker.internal:9000" -Dsonar.login="${SONAR_TOKEN}" -Dsonar.ws.timeout=120 -X
  only:
    - main
