stages:
  - build
  - test
  - sonarqube
  - deploy

variables:
  SONAR_HOST_URL: "http://192.168.0.101:9000"  # IP correto com porta
  SONAR_LOGIN: "${SONAR_TOKEN}"                # Token de autenticação
  DOCKER_NETWORK_MODE: "host"

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - sleep 10
    - echo "Tests complete."

sonarqube-job:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey="my_project_key" -Dsonar.sources="./src" -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.login="${SONAR_LOGIN}" -Dsonar.ws.timeout=120 -X
  only:
    - main
