name: First Pipeline \o/

on:
  push:
    branches:
      - main  # <-- trocado de 'main' para 'master'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: First Pipeline \o/
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: luizmgba/luizmgba:latest
      - name: Deploy na VM Oracle
        uses: appleboy/ssh-action@main
        with:
          host: 129.148.55.47
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u luizmgba -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull luizmgba/luizmgba:latest
            docker stop luizmgba-app || true
            docker rm luizmgba-app || true
            docker run -d -p 8080:8080 --name luizmgba-app luizmgba/luizmgba:latest